### PR TITLE
Moved patches from GDrive to Git repo

### PR DESCRIPTION
**Pull request by Sclafus**
I moved the patches from the GDrive to the Git repo in the appropriate folder
This helps a lot while trying to reproduce old builds, since GDrive files can be replaced without warning and/or be deleted

### CODE REVIEW

**Comment by NelloKudo** [comment]
That was something I was planning to do as well, but I wanted to leave the custompatches folder empty for users to move theirs in there and just compile. Maybe we can add them to osu-misc instead

**Comment by Sclafus** [comment]
They could add the custom patches along the original ones. It's not a problem and is more transparent for everyone involved in the project

**Comment by NelloKudo** [comment]
> They could add the custom patches along the original ones. It's not a problem and is more transparent for everyone involved in the project

Kinda lost myself on this, but I planned to create some sort of "Choose what wine version you want", then having every patch in a different folder would probably help. Whenever you're free please do that e.e

**Comment by Sclafus** [comment]
Probably not needed anymore, closing

**Pull request closed without merging**
